name: Run
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/**'
      - 'releases/**'

env:
  cache-version: v2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Get the youngest revision
        id: get_revision
        run: |
          REVISION=$(svn info  --no-newline --show-item revision http://svn.osdn.net/svnroot/ttssh2/)
          echo "revision=$REVISION" >> $GITHUB_ENV
          cat  $GITHUB_ENV

      - name: before cache
        run: |
          mkdir -p ttssh2
          ls ttssh2

      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.revision }}"
          echo "key        = ${{ env.cache-version }}-ttssh2-r${{ env.revision }}"
          echo "cache-hit  = ${{steps.cache-ttssh2.outputs.cache-hit}}"

      - name: Cache
        id: cache-svn
        uses: actions/cache@v3
        with:
          path: ttssh2
          key: ${{ env.cache-version }}-ttssh2-r${{ env.revision }}

      - name: mirror
        run: |
          echo "${{ env.revision }}"
          echo "key        = ${{ env.cache-version }}-ttssh2-r${{ env.revision }}"
          echo "cache-hit  = ${{steps.cache-ttssh2.outputs.cache-hit}}"
          ./mirror-ttssh2.sh

      - name: mirror-take2
        run: |
          echo "${{ env.revision }}"
          echo "key        = ${{ env.cache-version }}-ttssh2-r${{ env.revision }}"
          echo "cache-hit  = ${{steps.cache-ttssh2.outputs.cache-hit}}"
          ./mirror-ttssh2.sh


