name: Run
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/**'
      - 'releases/**'

env:
  cache-version: v1
  LANG: "ja_JP.UTF-8"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ja_JP.UTF-8
        run: |
            sudo locale-gen ja_JP.UTF-8
            sudo update-locale LANG=ja_JP.UTF-8
      - name: date
        run: |
            date

      # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Get the youngest revision
        id: get_revision
        run: |
          REVISION=$(svn info  --no-newline --show-item revision http://svn.osdn.net/svnroot/ttssh2/)
          echo "revision=$REVISION" >> $GITHUB_ENV
          cat  $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.revision }}"
      # See https://qiita.com/akubi0w1/items/2f4bf5d3ce7e5e77dfd7
      # cache保存用にディレクトリを作っておく
      - name: before cache
        run: |
          mkdir -p ttssh2
          ls ttssh2
      - name: Cache-ttssh2
        id: cache-ttssh2
        uses: actions/cache@v3
        env:
          cache-name: cache-ttssh2
        with:
          path: ttssh2
          key: ${{ env.cache-version }}-ttssh2

      - name: after cache
        run: |
          echo "key        = ${{ env.cache-version }}-ttssh2"
          echo "cache-hit  = ${{steps.Cache-ttssh2.outputs.cache-hit}}"
      - name: mirror
        run: ./mirror-ttssh2.sh
      - name: mirror-take2
        run: ./mirror-ttssh2.sh
